log:
  level: ERROR

accessLog:
  filePath: "/var/log/traefik/access.log"

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      email: "prof@{{ inventory_hostname }}"
      httpChallenge:
        entryPoint: http
